name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1

        with:
        envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_HOST: "postgres_sorteador_db"
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_DATABASE: "students-test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres_sorteador_db:5432/students-test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yaml run node_app npm run test